<Project>
  <PropertyGroup>
    <!-- The goal is to have the solution live inside a Unity project to make serialized references from .meta files work -->
    <!-- Need to avoid Visual Studio build output folders ending up inside of a Unity project -->
    <!-- Unity ignores folders that have a dot in front, so we override default folder names with names with a dot in front -->
    <BaseOutputPath>$(ProjectDir).bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(ProjectDir).obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>